I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 783, in script
    "As you drift to sleep once again, you see another blurry image appear before you but this time you can make out one particular feature, %(get_dream_desc())"
ValueError: incomplete format

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 783, in script
    "As you drift to sleep once again, you see another blurry image appear before you but this time you can make out one particular feature, %(get_dream_desc())"
  File "/Volumes/renpy-7.3.5-sdk/renpy-7.3.5-sdk/renpy/ast.py", line 708, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Volumes/renpy-7.3.5-sdk/renpy-7.3.5-sdk/renpy/exports.py", line 1334, in say
    what = what % tag_quoting_dict
ValueError: incomplete format

Darwin-20.1.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
Santa Dating Sim 1.0
Thu Dec 17 17:22:52 2020
